import { connectToMongo } from "./db.js"; // page pour connection à MongoDB

const db = await connectToMongo(); // Se connecter
const produitsCollection = db.collection("produit"); // Cherche la collection des produits

// Tableau des produits. Insert primaire
/*
{
    nom: '',
    prix: .00,
    details: '',
    type: '',
    sous_categorie: '',
    genre: '',
    tailleXS: ,
    tailleS: ,
    tailleM: ,
    tailleL: ,
    tailleXL: ,
    image_url1: '',
    image_url2: '',
    image_url3: '',
    quantite: 
  }, */

const produits = [
    {
        // ------------ BOTTOM FEMME ------------
        nom: 'Pantalon droit en jacquard de laine',
        prix: 1511.00,
        details: 'Jacquard de laine rose poudre, Agrafe, bouton et fermeture a glissiere dissimules sur le devant, 100% laine, Nettoyer a sec',
        type: 'Bas',
        sous_categorie: '',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Bas_femme/Bas_01A.png',
        image_url2: 'Images/Vetement_femme/Bas_femme/bottom_02A.png',
        image_url3: 'Images/Vetement_femme/Bas_femme/bottom_03A.png',
        quantite: 25
      },
      {
        nom: 'Jupe longue en jean',
        prix: 1198.00,
        details: 'Jean bleu clair, 100% coton',
        type: 'Bas',
        sous_categorie: '',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Bas_femme/Bas_01B.png',
        image_url2: 'Images/Vetement_femme/Bas_femme/bottom_02B.png',
        image_url3: 'Images/Vetement_femme/Bas_femme/bottom_03B.png',
        quantite: 25
      },
      {
        nom: 'Jupe mini en denim',
        prix: 1895.00,
        details: 'Denim bleu beige, cuir verni noir, 100% coton; garniture : 100% cuir',
        type: 'Bas',
        sous_categorie: '',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Bas_femme/Bas_01C.png',
        image_url2: 'Images/Vetement_femme/Bas_femme/Bas_02C.png',
        image_url3: 'Images/Vetement_femme/Bas_femme/Bas_03C.png',
        quantite: 25
      },
      {
        nom: 'Pantalon cargo taille haute en denim Boucle',
        prix: 215.00,
        details: 'Silhouette de pantalon cargo taille haute',
        type: 'Bas',
        sous_categorie: '',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Bas_femme/Bas_01D.png',
        image_url2: 'Images/Vetement_femme/Bas_femme/Bas_02D.png',
        image_url3: 'Images/Vetement_femme/Bas_femme/Bas_03D.png',
        quantite: 25
      },
      {
        nom: 'Pantalon en denim rouge',
        prix: 6200.00,
        details: 'Fermeture a glissiere avec agrafe, Poches avant en biais et poches arriere passepoilees',
        type: 'Bas',
        sous_categorie: '',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Bas_femme/Bas_01E.png',
        image_url2: 'Images/Vetement_femme/Bas_femme/Bas_02E.png',
        image_url3: 'Images/Vetement_femme/Bas_femme/Bas_03E.png',
        quantite: 25
      },
      {
        nom: 'Pantalon survetement',
        prix: 1100.00,
        details: '100% coton et elastique au niveau de la taille et des jambes',
        type: 'Bas',
        sous_categorie: 'Sportwear',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Bas_femme/Bas_01A.png',
        image_url2: '',
        image_url3: '',
        quantite: 25
      },
      {
        nom: 'Legging motif dentelle',
        prix: 1550.00,
        details: '80% polyester, 20% elasthanne Fabrique en Italie',
        type: 'Bas',
        sous_categorie: 'Sportwear',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Bas_femme/Bas_sportwear_01B.png',
        image_url2: 'Images/Vetement_femme/Bas_femme/Bas_sportwear_02B.png',
        image_url3: 'Images/Vetement_femme/Bas_femme/Bas_sportwear_03B.png',
        quantite: 25
      },
      {
        nom: 'Short',
        prix: 140.00,
        details: 'Convenant a tous les types de corps',
        type: 'Bas',
        sous_categorie: 'Sportwear',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Bas_femme/Bas_sportwear_01C.png',
        image_url2: 'Images/Vetement_femme/Bas_femme/Bas_sportwear_02C.png',
        image_url3: 'Images/Vetement_femme/Bas_femme/Bas_sportwear_03C.png',
        quantite: 25
      },

      // ------------ HAUT FEMME ------------
      {
        nom: 'Chandail en denim rouge',
        prix: 290.00,
        details: 'Chandail en denim rouge et ouverture en V sur le devant.',
        type: 'Haut',
        sous_categorie: '',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Haut_femme/Haut_01A.png',
        image_url2: 'Images/Vetement_femme/Haut_femme/Haut_02A.png',
        image_url3: 'Images/Vetement_femme/Haut_femme/Haut_03A.png',
        quantite: 25
      },
      {
        nom: 'Chemisier a manches flottantes',
        prix: 240.99,
        details: 'Chemisier a manches flottantes en melange de coton et de viscose tisse aere. Encolure ronde, ouverture goutte d eau a l arriere du cou avec bouton et plis sur la poitrine. Empiecement en dentelle delicate sur le haut et au-dessus de l ourlet.',
        type: 'Haut',
        sous_categorie: '',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Haut_femme/Haut_02A.png',
        image_url2: 'Images/Vetement_femme/Haut_femme/Haut_02B.png',
        image_url3: 'Images/Vetement_femme/Haut_femme/Haut_02C.png',
        quantite: 25
      },
      {
        nom: 'Veste Activewear avec SoftMove',
        prix: 440.99,
        details: 'Veste de sport courte et ajustee en tissu fonctionnel fabrique avec SoftMove pour une douceur et un confort ultimes ainsi qu un maintien des contours et DryMove pour evacuer l humidite de la peau. Col montant, fermeture eclair sur le devant avec protege-menton anti-frottements et manches extra-longues avec trous pour les pouces.',
        type: 'Haut',
        sous_categorie: 'Sportwear',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Haut_femme/Haut_sportwear_01A.png',
        image_url2: 'Images/Vetement_femme/Haut_femme/Haut_sportwear_02A.png',
        image_url3: 'Images/Vetement_femme/Haut_femme/Haut_sportwear_03A.png',
        quantite: 25
      },
      {
        nom: 'Haut court de sport avec DryMove',
        prix: 140.99,
        details: 'Haut de sport court et ajuste en tissu fonctionnel fabrique avec DryMove pour evacuer l humidite de la peau et vous garder confortablement au sec pendant vos mouvements.Encolure ronde et manches courtes.',
        type: 'Haut',
        sous_categorie: 'Sportwear',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Haut_femme/Top_sportwear_01A.png',
        image_url2: 'Images/Vetement_femme/Haut_femme/Top_sportwear_02B.png',
        image_url3: 'Images/Vetement_femme/Haut_femme/Top_sportwear_03C.png',
        quantite: 25
      },
      {
        nom: 'Soutien-gorge de yoga avec SoftMove',
        prix: .00,
        details: 'Soutien-gorge de yoga en tissu fonctionnel fabrique avec SoftMove pour une sensation de seconde peau qui met en valeur votre silhouette naturelle et technologie Lycra Sport pour plus d elasticite. Bretelles larges, col en V, bonnets doubles avec inserts amovibles pour un galbe et un ajustement ajustable, et elastique recouvert sur le bord inferieur avec un interieur doux et brosse. Maintien leger, adapte aux entrainements de faible intensite.',
        type: 'Haut',
        sous_categorie: 'Sportwear',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Haut_femme/Top_sportwear_01C.png',
        image_url2: 'Images/Vetement_femme/Haut_femme/Top_sportwear_02C.png',
        image_url3: 'Images/Vetement_femme/Haut_femme/Top_sportwear_03C.png',
        quantite: 25
      },
      {
        nom: 'Debardeur de sport en DryMove',
        prix: 220.99,
        details: 'Debardeur sans couture avec technologie DryMove pour une evacuation optimale de l humidite.',
        type: 'Haut',
        sous_categorie: 'Sportwear',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Haut_femme/Top_sportwear_01D.png', 
        image_url2: 'Images/Vetement_femme/Haut_femme/Top_sportwear_02D.png', 
        image_url3:'Images/Vetement_femme/Haut_femme/Top_sportwear_03D.png', 
        quantite: 25
      },
      {
        nom: 'Veste en shearling et cuir bleu minuit',
        prix: 1045.99,
        details: 'Veste ajustee avec epaules prononcees et encolure ronde. Se ferme avec une double fermeture eclair en laiton antique a l avant et finie avec un detail en relief du logo KNWLS sur l ourlet.',
        type: 'Haut',
        sous_categorie: 'Outerwear',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Haut_femme/Haut_outerwear_01A.png', 
        image_url2: 'Images/Vetement_femme/Haut_femme/Haut_outerwear_01B.png', 
        image_url3: 'Images/Vetement_femme/Haut_femme/Haut_outerwear_01C.png', 
        quantite: 25
      },
      {
        nom: 'Veste en cuir forme V',
        prix: 1300.99,
        details: 'Veste de motard a finition vintage en cuir noir craquele. Detaillee avec un ourlet en forme de corset et deux bandes en cuir suede beige surpiquees descendant des epaules aux poignets.',
        type: 'Haut',
        sous_categorie: 'Outerwear',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Haut_femme/Haut_outerwear_02A.png', 
        image_url2: 'Images/Vetement_femme/Haut_femme/Haut_outerwear_02B.png', 
        image_url3: 'Images/Vetement_femme/Haut_femme/Haut_outerwear_02C.png', 
        quantite: 25
      },
      {
        nom: 'Veste en denim courte avec col',
        prix: 1200.99,
        details: 'Veste en denim extensible et ajustee avec une construction a panneaux et un ourlet asymetrique. Fermeture eclair frontale et col large zippable. Manches trois-quarts detaillees avec fermetures eclair aux poignets.',
        type: 'Haut',
        sous_categorie: 'Outerwear',
        genre: 'Femme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_femme/Haut_femme/Haut_outerwear_03A.png',
        image_url2: 'Images/Vetement_femme/Haut_femme/Haut_outerwear_03B.png',
        image_url3: 'Images/Vetement_femme/Haut_femme/Haut_outerwear_03C.png',
        quantite: 25
      },

      // ------------ BOTTOM HOMME ------------
      {
        nom: 'Short en jean',
        prix: 150.00,
        details: 'Short en jean délavé gris avec taches de peinture blanches. Coupe ample. Braguette boutonnée. Passants de ceinture. Deux poches avant, deux poches arrière.',
        type: 'Bas',
        sous_categorie: '',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Bas_Homme/Bottom_01A.png',
        image_url2: 'Images/Vetement_homme/Bas_Homme/Bottom_01B.png',
        image_url3: 'Images/Vetement_homme/Bas_Homme/Bottom_01C.png',
        quantite: 25
      },
      {
        nom: 'Pantalon en jean avec chaînes décoratives',
        prix: 200.00,
        details: 'Pantalon en jean délavé bleu clair avec chaînes décoratives en plastique et métal. Effet usé. Coupe ample. Braguette boutonnée. Passants de ceinture. Deux poches avant, deux poches arrière. Détails de chaînes amovibles.',
        type: 'Bas',
        sous_categorie: '',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Bas_Homme/Bottom_02A.png',
        image_url2: 'Images/Vetement_homme/Bas_Homme/Bottom_02B.png',
        image_url3: 'Images/Vetement_homme/Bas_Homme/Bottom_02C.png',
        quantite: 25
      },
      {
        nom: 'Pantalon en jean déchiré et inscrit',
        prix: 250.00,
        details: 'Pantalon en jean délavé bleu clair avec déchirures importantes et inscriptions noires. Coupe très ample. Braguette boutonnée. Passants de ceinture. Deux poches avant, deux poches arrière. Détails d\'usure et d\'inscriptions graphiques.',
        type: 'Bas',
        sous_categorie: '',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Bas_Homme/Bottom_03A.png',
        image_url2: 'Images/Vetement_homme/Bas_Homme/Bottom_03B.png',
        image_url3: 'Images/Vetement_homme/Bas_Homme/Bottom_03C.png',
        quantite: 30
      },
      {
        nom: 'Pantalon en cuir',
        prix: 800.00,
        details: 'Pantalon en cuir vert olive avec fermetures éclair latérales. Coupe droite. Taille élastique avec cordon de serrage. Deux poches latérales. Détails de fermetures éclair argentées.',
        type: 'Bas',
        sous_categorie: '',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Bas_Homme/Bottom_04A.png',
        image_url2: 'Images/Vetement_homme/Bas_Homme/Bottom_04B.png',
        image_url3: 'Images/Vetement_homme/Bas_Homme/Bottom_04C.png',
        quantite: 25
      },
      {
        nom: 'Pantalon large en coton',
        prix: 350.00,
        details: 'Pantalon large en coton noir avec fines rayures ton sur ton. Coupe ample. Fermeture à agrafe et zip. Passants de ceinture. Deux poches latérales, deux poches arrière.',
        type: 'Bas',
        sous_categorie: '',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Bas_Homme/Bottom_05A.png',
        image_url2: 'Images/Vetement_homme/Bas_Homme/Bottom_05B.png',
        image_url3: 'Images/Vetement_homme/Bas_Homme/Bottom_05C.png',
        quantite: 30
      },
      {
        nom: 'Pantalon de survêtement brun',
        prix: 280.00,
        details: 'Pantalon de survêtement en coton marron délavé. Coupe large. Taille élastique avec cordon de serrage. Deux poches latérales. Finitions brutes.',
        type: 'Bas',
        sous_categorie: 'Sportwear',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Bas_Homme/Bottom_sportwear_01A.png',
        image_url2: 'Images/Vetement_homme/Bas_Homme/Bottom_sportwear_01B.png',
        image_url3: 'Images/Vetement_homme/Bas_Homme/Bottom_sportwear_01C.png',
        quantite: 25
      },
      {
        nom: 'Pantalon de survêtement gris',
        prix: 280.00,
        details: 'Pantalon de survêtement en coton gris foncé délavé. Coupe ample avec chevilles resserrées. Taille élastique avec cordon de serrage. Deux poches latérales. Finitions brutes.',
        type: 'Bas',
        sous_categorie: 'Sportwear',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Bas_Homme/Bottom_sportwear_02A.png',
        image_url2: 'Images/Vetement_homme/Bas_Homme/Bottom_sportwear_02B.png',
        image_url3: 'Images/Vetement_homme/Bas_Homme/Bottom_sportwear_02C.png',
        quantite: 35
      },
      {
        nom: 'Pantalon empiècements ondulés',
        prix: 420.00,
        details: 'Pantalon noir avec empiècements ondulés gris et marron. Coupe large. Taille élastique avec cordon de serrage. Deux poches latérales. Détail de cordon de serrage à l\'ourlet.',
        type: 'Bas',
        sous_categorie: 'Sportwear',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 1,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Bas_Homme/Bottom_sportwear_03A.png',
        image_url2: 'Images/Vetement_homme/Bas_Homme/Bottom_sportwear_03B.png',
        image_url3: 'Images/Vetement_homme/Bas_Homme/Bottom_sportwear_03C.png',
        quantite: 25
      },
      {
        nom: 'Pantalon survetement cargo',
        prix: 750.00,
        details: 'Pantalon cargo noir en serge de laine et coton melanges. Coupe large. Taille elastique avec cordon de serrage. Deux poches cargo laterales a rabat. Deux poches laterales. Detail de boutons pression a l\'ourlet.',
        type: 'Bas',
        sous_categorie: 'Sportwear',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Bas_Homme/Bottom_sportwear_04A.png', 
        image_url2: 'Images/Vetement_homme/Bas_Homme/Bottom_sportwear_04B.png', 
        image_url3: 'Images/Vetement_homme/Bas_Homme/Bottom_sportwear_04C.png', 
        quantite: 25
      },
      {
        nom: 'Pantalon de survetement noir avec design',
        prix: 550.00,
        details: 'Pantalon de survêtement noir en coton avec imprime graphique sur la jambe. Coupe droite. Taille elastique avec cordon de serrage. Deux poches laterales. Finitions cotelees.',
        type: 'Bas',
        sous_categorie: 'Sportwear',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Bas_homme/Bottom_sportwear_05A.png', 
        image_url2: 'Images/Vetement_homme/Bas_homme/Bottom_sportwear_05B.png', 
        image_url3: 'Images/Vetement_homme/Bas_homme/Bottom_sportwear_05C.png', 
        quantite: 25
      },

      //------------ HAUT HOMME ------------
      {
        nom: 'T-shirt avec trou',
        prix: 220.00,
        details: 'T-shirt gris foncé avec effet délavé et trous blancs. Coupe ample. Col rond. Manches courtes. Détails d\'usure.',
        type: 'Haut',
        sous_categorie: '',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Haut_homme/Top_01A.png',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'T-shirt imprimé In the Name of Light',
        prix: 180.00,
        details: 'T-shirt noir avec imprimé graphique blanc. Coupe ample. Col rond. Manches courtes. Inscription "In the Name of Light".',
        type: 'Haut',
        sous_categorie: '',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Haut_homme/Top_02A.png',
        image_url2: '',
        image_url3: '',
        quantite: 25
      },
      {
        nom: 'Maillot de couleur et manches de longues',
        prix: 380.00,
        details: 'Maillot à manches longues en maille imprimée multicolore. Coupe ample. Col en V. Manches longues avec poignets resserrés.',
        type: 'Haut',
        sous_categorie: '',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Haut_homme/Top_03A.png',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'Haut de rugby',
        prix: 250.00,
        details: 'Haut de rugby gris avec imprimé graphique blanc. Col polo blanc. Manches longues avec poignets resserrés. Détails de bandes noires. Coupe ample.',
        type: 'Haut',
        sous_categorie: '',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Haut_homme/Top_04A.png',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'Haut manches longues Satoshi Nakamoto',
        prix: 220.00,
       details: 'Haut à manches longues rayé multicolore. Imprimé "Satoshi Nakamoto" sur le devant. Coupe ample. Col rond. Manches longues. Détails de rayures décalées.',
        type: 'Haut',
        sous_categorie: '',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Haut_homme/Top_05A.png',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'T-shirt en maille',
        prix: 320.00,
        details: 'T-shirt à manches courtes superposé. Maille noire transparente sur t-shirt vert. Coupe ample. Col en V. Détails de fermeture éclair.',
        type: 'Haut',
        sous_categorie: 'sportwear',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Haut_homme/Top_sportwear_01A.png',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'Haut manches longues Thermal',
        prix: 110.00,
        details: 'Haut à manches longues noir en laine mérinos. Fermeture éclair au col. Coupe ajustée. Manches longues avec poignets resserrés. Détails de coutures plates. Respirant et thermorégulant.',
        type: 'Haut',
        sous_categorie: 'sportwear',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Haut_homme/Top_sportwear_02A.png',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'T-shirt Vegyn Nauseous Devlish',
        prix: 80.00,
        details: 'T-shirt noir avec imprimé graphique blanc. Inscription "nouscous DEVILISH". Illustration de la faucheuse. Coupe ample. Col rond. Manches courtes.',
        type: 'Haut',
        sous_categorie: 'sportwear',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Haut_homme/Top_sportwear_03A.png',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'T-shirt sans manches',
        prix: 280.00,
        details: 'T-shirt noir sans manches en maille. Coupe asymétrique. Détails de boutons pression. Col rond. Ourlet fendu.',
        type: 'Haut',
        sous_categorie: 'sportwear',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Haut_homme/Top_sportwear_04A.png',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'T-shirt imprimé graphique',
        prix: 350.00,
        details: 'T-shirt blanc avec imprimé graphique bleu. Chevalier à cheval. Coupe classique. Col rond. Manches courtes. 100% coton.',
        type: 'Haut',
        sous_categorie: 'sportwear',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Haut_homme/Top_sportwear_05A.png',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'Manteau brillant à simple boutonnage',
        prix: 950.00,
        details: 'Manteau noir brillant à simple boutonnage. Coupe classique. Revers crantés. Fermeture boutonnée. Deux poches avant à rabat. Doublure intérieure. 100% polyuréthane.',
        type: 'Haut',
        sous_categorie: 'Outerwear',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Haut_homme/Top_outwear_01A.png',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'Blouson aviateur à logo brodé',
        prix: 850.00,
        details: 'Blouson aviateur vert olive en satin. Logo brodé sur la manche. Coupe classique. Fermeture éclair. Col, poignets et ourlet côtelés. Deux poches avant à rabat. Doublure intérieure. 100% polyester.',
        type: 'Haut',
        sous_categorie: 'Outerwear',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Haut_homme/Top_outwear_02A.png',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'Veste en cuir craquelé bordée de peau lainée',
        prix: 1500.00,
        details: 'Veste noire en cuir craquelé avec bordure en peau lainée. Coupe courte. Fermeture éclair. Col montant en peau lainée. Deux poches latérales. Doublure intérieure. 100% cuir d\'agneau.',
        type: 'Haut',
        sous_categorie: 'Outerwear',
        genre: 'Homme',
        tailleXS: 5,
        tailleS: 5,
        tailleM: 5,
        tailleL: 5,
        tailleXL: 5,
        image_url1: 'Images/Vetement_homme/Haut_homme/Top_outwear_03A.png',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },

      // ------------ SAC ------------
      // -- Pochette
      {
        nom: 'Pochette noire a anneau',
        prix: 1400.00,
        details: 'Sac a poignee superieure en cuir d\'agneau poli, couleur noire.',
        type: 'Sac',
        sous_categorie: 'Pochette',
        genre: 'Femme',
        image_url1: 'Images/Produit-Accessoires/clutch1.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 10
      },
      {
        nom: 'Pochette noire asymetrique oversize',
        prix: 1800.00,
        details: 'Pochette structuree en cuir d\'agneau verni froisse, couleur noire.',
        type: 'Sac',
        sous_categorie: 'Pochette',
        genre: 'Femme',
        image_url1: 'Images/Produit-Accessoires/clutch2.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 5
      },
      {
        nom: 'Pochette rose pale',
        prix: 2600.00,
        details: 'Pochette en cuir d\'agneau graine, couleur rose.',
        type: 'Sac',
        sous_categorie: 'Pochette',
        genre: 'Femme',
        image_url1: 'Images/Produit-Accessoires/clutch3.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 13
      },
      {
        nom: 'Pochette rouge à imprime croco',
        prix: 2100.00,
        details: 'Pochette en cuir de veau embosse facon crocodile, couleur rouge.',
        type: 'Sac',
        sous_categorie: 'Pochette',
        genre: 'Unisexe',
        image_url1: 'Images/Produit-Accessoires/clutch4.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 20
      },
      {
        nom: 'Pochette palette de peinture multicolore',
        prix: 890.00,
        details: 'Pochette sculpturale en faux cuir graine, couleur noire.',
        type: 'Sac',
        sous_categorie: 'Pochette',
        genre: 'Unisexe',
        image_url1: 'Images/Produit-Accessoires/clutch5.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 15
      },
      // -- Bandouliere
      {
        nom: 'Sac bandouliere ergonomique',
        prix: 750.00,
        details: 'Sac bandouliere en cuir de veau embossee facon crocodile, couleur beige.',
        type: 'Sac',
        sous_categorie: 'Bandouliere',
        genre: 'Femme',
        image_url1: 'Images/Produit-Accessoires/shoulder1.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 20
      },
      {
        nom: 'Mini sac bandouliere noir',
        prix: 450.00,
        details: 'Sac bandouliere en cuir poli, couleur noire.',
        type: 'Sac',
        sous_categorie: 'Bandouliere',
        genre: 'Femme',
        image_url1: 'Images/Produit-Accessoires/shoulder2.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 40
      },
      {
        nom: 'Sac bandouliere cargo marron',
        prix: 500.00,
        details: 'Sac bandouliere en cuir graine, couleur marron.',
        type: 'Sac',
        sous_categorie: 'Bandouliere',
        genre: 'Femme',
        image_url1: 'Images/Produit-Accessoires/shoulder3.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'Sac bandouliere rose et noire avec breloque',
        prix: 800.00,
        details: 'Sac bandouliere en coton seersucker, couleurs rose et noire, avec breloque.',
        type: 'Sac',
        sous_categorie: 'Bandouliere',
        genre: 'Femme',
        image_url1: 'Images/Produit-Accessoires/shoulder4.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 10
      },
      {
        nom: 'Sac micro brag gris multi-poches',
        prix: 450.00,
        details: 'Sac a poignee superieure en cuir de veau suede lamine, couleur grise.',
        type: 'Sac',
        sous_categorie: 'Bandouliere',
        genre: 'Femme',
        image_url1: 'Images/Produit-Accessoires/shoulder5.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'Sac bandouliere plie bordeaux',
        prix: 650.00,
        details: 'Sac a poignee superieure en cuir d\'agneau graine verni, confectionne a la main, couleur bordeaux.',
        type: 'Sac',
        sous_categorie: 'Bandouliere',
        genre: 'Unisexe',
        image_url1: 'Images/Produit-Accessoires/shoulder6.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 35
      },
      {
        nom: 'Grand sac bandouliere croissant marron',
        prix: 570.00,
        details: 'Sac bandouliere en toile de coton enduite, couleur marron.',
        type: 'Sac',
        sous_categorie: 'Bandouliere',
        genre: 'Unisexe',
        image_url1: 'Images/Produit-Accessoires/shoulder7.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 20
      },
      {
        nom: 'Sac bandouliere boucle violet',
        prix: 890.00,
        details: 'Sac bandouliere en suede, couleur violette, avec sangle a boucle.',
        type: 'Sac',
        sous_categorie: 'Bandouliere',
        genre: 'Femme',
        image_url1: 'Images/Produit-Accessoires/shoulder8.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 10 
      },
      {
        nom: 'Sac bandouliere en cuir marron',
        prix: 560.00,
        details: 'Sac bandouliere en cuir poli, couleur marron.',
        type: 'Sac',
        sous_categorie: 'Bandouliere',
        genre: 'Femme',
        image_url1: 'Images/Produit-Accessoires/shoulder9.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 20
      },
      {
        nom: '',
        prix: .00,
        details: '',
        type: 'Sac',
        sous_categorie: 'Bandouliere',
        genre: 'Unisexe',
        image_url1: 'Images/Produit-Accessoires/shoulder10.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      // -- Tote
      {
        nom: 'Tote noir a boucle de ceinture',
        prix: 940.00,
        details: 'Sac tote en cuir graine, couleur noire. Boucle de ceinture et attache pour cle.',
        type: 'Sac',
        sous_categorie: 'Tote',
        genre: 'Unisexe',
        image_url1: 'Images/Produit-Accessoires/tote1.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 40
      },
      {
        nom: 'Tote en denim bleu avec breloques',
        prix: 945.00,
        details: 'Sac tote en toile de coton, couleur bleue.',
        type: 'Sac',
        sous_categorie: 'Tote',
        genre: 'Unisexe',
        image_url1: 'Images/Produit-Accessoires/tote2.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 50
      },
      {
        nom: 'Tote cargo noir',
        prix: 650.00,
        details: 'Sac tote en cuir de veau froisse et taffetas de nylon, couleur noire.',
        type: 'Sac',
        sous_categorie: 'Tote',
        genre: 'Unisexe',
        image_url1: 'Images/Produit-Accessoires/tote3.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 50
      },
      {
        nom: 'Tote drape en coton noir',
        prix: 730.00,
        details: 'Sac tote en toile de coton, couleur noire.',
        type: 'Sac',
        sous_categorie: 'Tote',
        genre: 'Unisexe',
        image_url1: 'Images/Produit-Accessoires/tote4.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'Tote froisse kaki',
        prix: 600.00,
        details: 'Sac tote en cuir verni froisse, couleur kaki.',
        type: 'Sac',
        sous_categorie: 'Tote',
        genre: 'Unisexe',
        image_url1: 'Images/Produit-Accessoires/tote1.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 40
      },
      // ------------ ACCESSOIRE ------------
      // -- Bracelets
      {
        nom: 'Bracelet triptyque argent',
        prix: 400.00,
        details: 'Bracelet manchette ouvert a plusieurs niveaux en cuivre plaque rhodium.',
        type: 'accessoire',
        sous_categorie: 'bracelet',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/bracelet1.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 25
      },
      {
        nom: 'Bracelet carre dore',
        prix: 240.00,
        details: 'Bracelet manchette en laiton dore pale.',
        type: 'accessoire',
        sous_categorie: 'bracelet',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/bracelet2.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 20
      },
      {
        nom: 'Bracelet Barbara argent avec agate',
        prix: 650.00,
        details: 'Bracelet manchette sculptural fait main en argent sterling et pierre d\'agate du Botswana.',
        type: 'accessoire',
        sous_categorie: 'bracelet',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/bracelet3.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 15
      },
      {
        nom: 'Bracelet a gros maillons argent',
        prix: 480.00,
        details: 'Bracelet en chaine a gros maillons en laiton argente.',
        type: 'accessoire',
        sous_categorie: 'bracelet',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/bracelet4.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 40
      },
      {
        nom: 'Bracelet spirale dore',
        prix: 350.00,
        details: 'Bracelet manchette ouvert en argent sterling plaque or 18 carats.',
        type: 'accessoire',
        sous_categorie: 'bracelet',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/bracelet5.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },

      // -- Chapeaux
      {
        nom: 'Casquette Gavroche en denim noir',
        prix: 250.00,
        details: 'Casquette en denim non extensible noir. 100% coton. Fabrique au Canada.',
        type: 'accessoire',
        sous_categorie: 'chapeau',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/chapeau1.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },
      {
        nom: 'Casquette en denim bleu et beige',
        prix: 155.00,
        details: 'Une casquette en denim extensible bleu et beige. Fabrique au Canada.',
        type: 'accessoire',
        sous_categorie: 'chapeau',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/chapeau2.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 20
      },
      {
        nom: 'Bonnet raye beige et noir',
        prix: 200.00,
        details: 'Bonnet en tricot cotele en melange de coton et viscose, beige et noir. 61% coton, 27% viscose, 12% polyester. Fabrique au Canada.',
        type: 'accessoire',
        sous_categorie: 'chapeau',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/chapeau3.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 25
      },
      {
        nom: 'Cagoule en cachemire noir',
        prix: 300.00,
        details: 'Cagoule en maille brossee 100% cachemire noir. Fabrique au Canada.',
        type: 'accessoire',
        sous_categorie: 'chapeau',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/chapeau4.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 15
      },
      {
        nom: 'Casquette noire delavee avec logo',
        prix: 100.00,
        details: 'Casquette en serge de coton noir. Delavage et effet vieilli partout. 100% coton. Fabrique au Canada.',
        type: 'accessoire',
        sous_categorie: 'chapeau',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/chapeau5.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 30
      },

      // -- Colliers
      {
        nom: 'Ras-de-cou blanc a perles synthetiques et cœur',
        prix: 500.00,
        details: 'Ras-de-cou superpose perles synthetiques blanches, cristaux en verre sur pendentif. Plastique, verre, laiton. Fabrique en Italie.',
        type: 'accessoire',
        sous_categorie: 'collier',
        genre: 'femme',
        image_url1: 'Images/Produit-Accessoires/collier1.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 10
      },
      {
        nom: 'Collier hibiscus noir',
        prix: 200.00,
        details: 'Collier artisanal en cordon noir. Pendentif graphique en verre texture. Textile, verre borosilicate. Fabrique en Italie.',
        type: 'accessoire',
        sous_categorie: 'collier',
        genre: 'femme',
        image_url1: 'Images/Produit-Accessoires/collier2.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 15
      },
      {
        nom: 'Collier en or avec perles et diamant',
        prix: 1500.00,
        details: 'Chaine fine en or 14k. Pendentif diamants et perles eau douce. Or. Fabrique aux Etats-Unis.',
        type: 'accessoire',
        sous_categorie: 'collier',
        genre: 'femme',
        image_url1: 'Images/Produit-Accessoires/collier3.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 5
      },
      {
        nom: 'Collier chaine argent a maillons pointus',
        prix: 600.00,
        details: 'Collier artisanal a maillons textures en argent sterling 925. Fabrique en Italie.',
        type: 'accessoire',
        sous_categorie: 'collier',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/collier4.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 20
      },
      {
        nom: 'Collier double chaine minimaliste en or',
        prix: 400.00,
        details: 'Collier superpose en chaines gourmette fines et epaisses en laiton dore. Fabrique en Italie.',
        type: 'accessoire',
        sous_categorie: 'collier',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/collier5.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 50
      },

    // -- Boucles d'oreille
      {
        nom: 'Boucles d\'oreilles pendantes de coquillage',
        prix: 155.00,
        details: 'Paire de boucles d\'oreilles pendantes en argent sterling. Fabrique au Canada.',
        type: 'accessoire',
        sous_categorie: 'boucles',
        genre: 'femme',
        image_url1: 'Images/Produit-Accessoires/boucles1.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 20
      },
      {
        nom: 'Boucles d\'oreilles dorees en forme de nœud',
        prix: 150.00,
        details: 'Paire de boucles d\'oreilles clous en laiton plaque or 14k. Fabrique au Canada.',
        type: 'accessoire',
        sous_categorie: 'boucles',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/boucles2.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 50
      },
      {
        nom: 'Boucles d\'oreilles pendantes a nœud et cristaux',
        prix: 130.00,
        details: 'Paire de boucles d\'oreilles pendantes asymetriques artisanales en laiton plaque palladium. Fabrique en France.',
        type: 'accessoire',
        sous_categorie: 'boucles',
        genre: 'femme',
        image_url1: 'Images/Produit-Accessoires/boucles3.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 40
      },
      {
        nom: 'Boucles d\'oreilles monogramme dorees',
        prix: 300.00,
        details: 'Paire de boucles d\'oreilles pendantes en metal à ton dore.',
        type: 'accessoire',
        sous_categorie: 'boucles',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/boucles4.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 20
      },
      {
        nom: 'Boucles d\'oreilles fleurs vertes',
        prix: 330.00,
        details: 'Paire de boucles d\'oreilles clous artisanales en vermeil d\'or blanc 18k. Fabrique en Italie.',
        type: 'accessoire',
        sous_categorie: 'boucles',
        genre: 'unisexe',
        image_url1: 'Images/Produit-Accessoires/boucles5.jpg',
        image_url2: '',
        image_url3: '',
        quantite: 20
      },

      
];
/*
  {
    nom: '',
    prix: .00,
    details: '',
    type: '',
    sous_categorie: '',
    genre: '',
    tailleXS: ,
    tailleS: ,
    tailleM: ,
    tailleL: ,
    tailleXL: ,
    image_url1: '',
    image_url2: '',
    image_url3: '',
    quantite: 
  },
*/

// Si le produit existe, ça va update.
// Si le produit n'existe pas, ça va insert
for (const produit of produits) {
    await produitsCollection.updateOne(
        { nom: produit.nom }, 
        { $set: produit },
        { upsert: true }
    );
}

console.log("Produits insérés/mis à jour avec succès !");
